[fix] Fixed accessibility issues of notification widget #112
openwisp/openwisp-notifications pull request #124
Opened 2020-09-07 11:43 UTC by pandafy

Fixed notification bell and notification element not accessible from keyboard.
Added handlers for key events.

Closes #112

2020-09-07 11:46 UTC, pandafy commented
![Hnet-image (14)](https://user-images.githubusercontent.com/32094433/92384321-7f501b00-f12d-11ea-8987-d7997f7cfc07.gif)

2020-09-07 11:47 UTC, TravisBuddy commented
## Travis tests have failed

Hey @pandafy,
Please read the following log in order to understand the failure reason.
It'll be awesome if you fix what's wrong and commit the changes.


### 1st Build

<a href="https:&#x2F;&#x2F;travis-ci.org&#x2F;openwisp&#x2F;openwisp-notifications&#x2F;jobs&#x2F;724894630">View build log</a>


<details>
  <summary>
    <strong>
     coverage run -a --source&#x3D;openwisp_notifications runtests.py
    </strong>
  </summary>

```
Creating test database for alias 'default'...
System check identified no issues (0 silenced).
......................'User' object has no attribute 'random'
'User' object has no attribute 'random'
Error in rendering notification message.
'User' object has no attribute 'random'
'User' object has no attribute 'random'
Error in rendering notification message.
......'NoneType' object has no attribute 'pk'
Error in rendering notification message.
..................................'User' object has no attribute 'random'
'User' object has no attribute 'random'
Error in rendering notification message.
...................
Summary of slow tests (>0.3s)

(openwisp_notifications.tests.test_admin.TestAdmin)
  (0.67s) test_org_admin_view_same_org_user_notification_setting
(openwisp_notifications.tests.test_api.TestNotificationApi)
  (0.40s) test_bearer_authentication
  (0.59s) test_list_notification_api
  (0.31s) test_list_view_notification_cache
  (0.33s) test_notification_recipients
(openwisp_notifications.tests.test_notification_setting.TestNotificationSetting)
  (0.33s) test_post_migration_handler
(openwisp_notifications.tests.test_notifications.TestNotifications)
  (0.55s) test_group_recipient
  (0.38s) test_inactive_user_not_receive_notification
  (0.34s) test_no_organization
  (0.46s) test_notification_received_only_by_org_admin
  (0.32s) test_organization_recipient

Total slow tests detected: 11

----------------------------------------------------------------------
Ran 81 tests in 15.783s

OK
Destroying test database for alias 'default'...
============================= test session starts ==============================
platform linux -- Python 3.6.10, pytest-5.4.3, py-1.8.0, pluggy-0.13.1
django: settings: openwisp2.settings (from env)
rootdir: /home/travis/build/openwisp/openwisp-notifications, inifile: setup.cfg
plugins: asyncio-0.14.0, django-3.9.0, celery-4.4.7
collected 6 items                                                              

openwisp_notifications/tests/test_websockets.py ..F...                   [100%]

=================================== FAILURES ===================================
_______________ TestNotificationSockets.test_delete_notification _______________

self = <django.db.backends.utils.CursorWrapper object at 0x7fd20106ee48>
sql = 'SELECT COUNT(*) AS "__count" FROM "openwisp_notifications_notification" WHERE ("openwisp_notifications_notification"."recipient_id" = %s AND "openwisp_notifications_notification"."unread" = %s)'
params = ('ccee2c3872824c4083daa084012b15eb', True)
ignored_wrapper_args = (False, {'connection': <django.db.backends.sqlite3.base.DatabaseWrapper object at 0x7fd20141b630>, 'cursor': <django.db.backends.utils.CursorWrapper object at 0x7fd20106ee48>})

    def _execute(self, sql, params, *ignored_wrapper_args):
        self.db.validate_no_broken_transaction()
        with self.db.wrap_database_errors:
            if params is None:
                return self.cursor.execute(sql)
            else:
>               return self.cursor.execute(sql, params)

../../../virtualenv/python3.6.10/lib/python3.6/site-packages/django/db/backends/utils.py:84: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

self = <django.db.backends.sqlite3.base.SQLiteCursorWrapper object at 0x7fd201795318>
query = 'SELECT COUNT(*) AS "__count" FROM "openwisp_notifications_notification" WHERE ("openwisp_notifications_notification"."recipient_id" = ? AND "openwisp_notifications_notification"."unread" = ?)'
params = ('ccee2c3872824c4083daa084012b15eb', True)

    def execute(self, query, params=None):
        if params is None:
            return Database.Cursor.execute(self, query)
        query = self.convert_query(query)
>       return Database.Cursor.execute(self, query, params)
E       sqlite3.OperationalError: database table is locked: openwisp_notifications_notification

../../../virtualenv/python3.6.10/lib/python3.6/site-packages/django/db/backends/sqlite3/base.py:383: OperationalError

The above exception was the direct cause of the following exception:

self = <openwisp_notifications.tests.test_websockets.TestNotificationSockets object at 0x7fd2012b8f28>
admin_user = <User: admin>
admin_client = <django.test.client.Client object at 0x7fd2010d8358>

    async def test_delete_notification(self, admin_user, admin_client):
        n = await create_notification(admin_user)
        communicator = await self._get_communicator(admin_client)
        await notification_operation(n, delete=True)
>       response = await communicator.receive_json_from()

openwisp_notifications/tests/test_websockets.py:78: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
../../../virtualenv/python3.6.10/lib/python3.6/site-packages/channels/testing/websocket.py:93: in receive_json_from
    payload = await self.receive_from(timeout)
../../../virtualenv/python3.6.10/lib/python3.6/site-packages/channels/testing/websocket.py:72: in receive_from
    response = await self.receive_output(timeout)
../../../virtualenv/python3.6.10/lib/python3.6/site-packages/asgiref/testing.py:70: in receive_output
    self.future.result()
../../../virtualenv/python3.6.10/lib/python3.6/site-packages/asgiref/compatibility.py:34: in new_application
    return await instance(receive, send)
../../../virtualenv/python3.6.10/lib/python3.6/site-packages/channels/sessions.py:183: in __call__
    return await self.inner(receive, self.send)
../../../virtualenv/python3.6.10/lib/python3.6/site-packages/channels/middleware.py:41: in coroutine_call
    await inner_instance(receive, send)
../../../virtualenv/python3.6.10/lib/python3.6/site-packages/channels/consumer.py:59: in __call__
    [receive, self.channel_receive], self.dispatch
../../../virtualenv/python3.6.10/lib/python3.6/site-packages/channels/utils.py:51: in await_many_dispatch
    await dispatch(result)
../../../virtualenv/python3.6.10/lib/python3.6/site-packages/asgiref/sync.py:296: in __call__
    ret = await asyncio.wait_for(future, timeout=None)
/opt/python/3.6.10/lib/python3.6/asyncio/tasks.py:339: in wait_for
    return (yield from fut)
/opt/python/3.6.10/lib/python3.6/concurrent/futures/thread.py:56: in run
    result = self.fn(*self.args, **self.kwargs)
../../../virtualenv/python3.6.10/lib/python3.6/site-packages/channels/db.py:14: in thread_handler
    return super().thread_handler(loop, *args, **kwargs)
../../../virtualenv/python3.6.10/lib/python3.6/site-packages/asgiref/sync.py:334: in thread_handler
    return func(*args, **kwargs)
../../../virtualenv/python3.6.10/lib/python3.6/site-packages/channels/consumer.py:105: in dispatch
    handler(message)
openwisp_notifications/websockets/consumers.py:39: in send_updates
    user.notifications.unread().count()
../../../virtualenv/python3.6.10/lib/python3.6/site-packages/django/db/models/query.py:392: in count
    return self.query.get_count(using=self.db)
../../../virtualenv/python3.6.10/lib/python3.6/site-packages/django/db/models/sql/query.py:504: in get_count
    number = obj.get_aggregation(using, ['__count'])['__count']
../../../virtualenv/python3.6.10/lib/python3.6/site-packages/django/db/models/sql/query.py:489: in get_aggregation
    result = compiler.execute_sql(SINGLE)
../../../virtualenv/python3.6.10/lib/python3.6/site-packages/django/db/models/sql/compiler.py:1142: in execute_sql
    cursor.execute(sql, params)
../../../virtualenv/python3.6.10/lib/python3.6/site-packages/django/db/backends/utils.py:67: in execute
    return self._execute_with_wrapp [...]

2020-09-10 02:54 UTC, nemesisdesign requested changes
This is great!

I have one request, can you make the add the :focus style to so that it's the same as the :hover for all the clickable elements in the widget? This will cause the elements to change color as if the mouse is moving over them, which basically allows to browse the widget with the keyboard and have the same experience as with the mouse.

2020-09-14 18:07 UTC, nemesisdesign approved these changes
Thanks! :+1:

2020-09-14 18:19 UTC, merged