Issues/171 email send exception handling
openwisp/openwisp-notifications pull request #174
Opened 2021-03-13 12:36 UTC by RahulPalve

Added exception handling in mail send, This will log any exception happend while sending mail

2021-03-13 12:44 UTC, Purhan requested changes
Thanks @RahulPalve 
Please reference the issue properly in the commit message/PR description
Also check my comment below

2021-03-13 12:44 UTC, Purhan commented on openwisp_notifications/handlers.py
> +        logger.exception('Notification email sending failed :' + str(e))
We generally use the f-string convention:

```python
logger.exception(f'Notification email sending failed : {str(e)}')
```

2021-04-12 04:01 UTC, pandafy requested changes
@RahulPalve the build is failing due to QA issues. Locally, run `openwisp-qa-format` to format the code and `./run-qa-checks` to confirm your patch follows OpenWISP"s QA standards. You will have to fix those errors for CI build to pass. 

Read ["How to commit your changes properly" section of OpenWISP's contribution guidelines](https://openwisp.io/docs/developer/contributing.html#how-to-commit-your-changes-properly) if you already haven't.

It will also be nice to have a test for such scenario. Let us know if you need help writing test for this. If you get stuck, feel free to ask for help on [OpenWISP's Gitter channel](https://gitter.im/openwisp/general) or this PR.

2021-05-30 11:21 UTC, pandafy requested changes
Tests are missing. If you have any trouble in writing tests, feel free to ask for help in [OpenWISP's Gitter chat](https://gitter.im/openwisp/general).

2021-05-30 11:22 UTC, pandafy requested changes
Tests are missing. If you have any trouble in writing tests, feel free to ask for help in [OpenWISP's Gitter chat](https://gitter.im/openwisp/general).

2021-05-30 11:22 UTC, pandafy commented on openwisp_notifications/handlers.py
> +
```suggestion
```

2021-05-30 11:22 UTC, pandafy commented on openwisp_notifications/handlers.py
> +
```suggestion
```

2021-10-05 10:52 UTC, pandafy commented
Closing PR due to lack of activity.

2021-10-05 10:52 UTC, closed without merging