[bug] Error handling send_email_notification #179
openwisp/openwisp-notifications pull request #180
Opened 2021-05-12 12:57 UTC by RahulPalve

Added exception handling in send_email_notification, So if
`notification_setting = instance.recipient.notificationsetting_set.get(
                organization=target_org, type=instance.type
            )` 
NotificationSetting Does Not Exist it will return from function and mail will not be sent.

2021-05-13 20:46 UTC, nemesisdesign requested changes
Great, but a test for the bug is missing.

2021-05-21 12:23 UTC, RahulPalve commented
hey @nemesisdesign, I didn't understand  "test case for a bug". Should I write a test case which is checking that code is generating `DoesNotExist` Exception in case  `notification_setting` does not exist? I am new to openwisp-notification please assist.

2021-05-21 17:35 UTC, nemesisdesign reviewed
> hey @nemesisdesign, I didn't understand "test case for a bug". Should I write a test case which is checking that code is generating `DoesNotExist` Exception in case `notification_setting` does not exist? I am new to openwisp-notification please assist.

Hi @RahulPalve,

whenever we fix bug, the first thing we do is to write a test that fails and replicate the bug. You can write it also afterwards, you just need to comment your changes and restore the old version, write the failing test, then uncomment the fix and the test should pass.

Is it clearer now?

2021-05-30 11:35 UTC, pandafy requested changes
Tests are missing. If you have any trouble in writing tests, feel free to ask for help in [OpenWISP's Gitter chat](https://gitter.im/openwisp/general).

2021-10-05 10:48 UTC, closed without merging

2021-10-05 10:49 UTC, pandafy commented
Closing this due to lack of activity.