[deps] Added support for Django 3.2 and 4.0 #194
openwisp/openwisp-notifications pull request #214
Opened 2021-12-17 13:04 UTC by pandafy

Closes #194

Depends  on https://github.com/django-notifications/django-notifications/pull/323

2021-12-17 13:05 UTC, pandafy commented on requirements.txt
> +django-notifications-hq @ https://github.com/siemens/django-notifications/tarball/fix-signals-compatible-django-4-0
TODO: Change this to master branch.

2021-12-19 20:49 UTC, nemesisdesign requested changes

2021-12-19 20:49 UTC, nemesisdesign commented on requirements.txt
> +django-notifications-hq @ https://github.com/siemens/django-notifications/tarball/fix-signals-compatible-django-4-0
please proceed

2021-12-26 20:54 UTC, nemesisdesign approved these changes
Tested and works fine :+1:

2021-12-26 21:10 UTC, merged