[qa] Enable linting for css and js #185
openwisp/openwisp-notifications pull request #218
Opened 2022-01-19 13:10 UTC by yashikajotwani12

Fixes #185

2022-01-25 18:30 UTC, nemesisdesign requested changes
@yashikajotwani12 please double check your version of black, it seems it's not in line with what the CI uses and hence there are differences which are being rejected by the qa checks.

2022-01-26 06:39 UTC, yashikajotwani12 commented
> @yashikajotwani12 please double check your version of black, it seems it's not in line with what the CI uses and hence there are differences which are being rejected by the qa checks.

Okay! Trying to improve this.

2022-01-26 08:54 UTC, yashikajotwani12 commented
> @yashikajotwani12 please double check your version of black, it seems it's not in line with what the CI uses and hence there are differences which are being rejected by the qa checks.

I have checked and it aligns with the version which CI uses.

2022-02-12 14:32 UTC, nemesisdesign approved these changes

2022-02-12 14:33 UTC, merged