Error handling send_email_notification fixed #179
openwisp/openwisp-notifications pull request #222
Opened 2022-02-03 14:08 UTC by aagman945

Added exception handling for the issue #179 and test for the same . So ,If throws exception the function will be returned empty and mail will not be sent.

2022-02-03 14:28 UTC, pandafy requested changes
@aagman945 kindly **read the contributing guidelines** and update your editor settings as mentioned here https://openwisp.io/docs/developer/contributing.html#avoiding-unnecessary-changes. 

Doing so would have reduced requested changes in this PR. The commit message needs to be updated as well. 

Also, always run `./run-qa-check` before pushing changes to GitHub.

2022-02-03 14:28 UTC, pandafy commented on openwisp_notifications/tests/test_notifications.py
> +        )
We don't need to add a dedicated test class here. You can add this test to `TestTransactionNotifications` class. 

P.S.: The python convention is to use PascalCase for naming classes not snake_case. Refer https://namingconvention.org/python/

2022-02-04 07:42 UTC, aagman945 commented
@pandafy ./run-qa-checks throws error 
TypeError: [files].flat is not a function
at standalone (/usr/local/lib/node_modules/stylelint/lib/standalone.js:158:25)
at module.exports (/usr/local/lib/node_modules/stylelint/lib/cli.js:484:9)
at Object.<anonymous> (/usr/local/lib/node_modules/stylelint/bin/stylelint.js:8:22)
at Module._compile (internal/modules/cjs/loader.js:778:30)
at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
at Module.load (internal/modules/cjs/loader.js:653:32)
at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
at Function.Module._load (internal/modules/cjs/loader.js:585:3)
at Function.Module.runMain (internal/modules/cjs/loader.js:831:12)
at startup (internal/bootstrap/node.js:283:19)

2022-02-11 15:02 UTC, pandafy requested changes

2022-02-11 15:02 UTC, pandafy commented on openwisp_notifications/tests/test_notifications.py
> +
@aagman945 this test does not trigger the bug. The bug only appears if notification setting is not present for the  user. 

In the end of the test, you are assert for presence of one email. But we don't want an email to be sent in this scenario. This depicts that the test does not tests the exception handling that  you just added. 

I would change this test as following:

```suggestion
def test_email_notification_without_notification_setting(self):
        target_obj = self._get_org_user()
        data = dict(
            email_subject='Test Email subject', url='https://localhost:8000/admin'
        )
        # Delete notification settings of the recipient
        self.admin.notificationsetting_set.all().delete()
        Notification.objects.create(
            actor=self.admin,
            recipient=self.admin,
            description='Test Notification Description',
            verb='Test Notification',
            action_object=target_obj,
            target=target_obj,
            data=data,
            type="default",
        )
        self.assertEqual(len(mail.outbox), 0)
```

2022-02-11 15:43 UTC, pandafy approved these changes

2022-02-11 15:46 UTC, merged