chore: relative url for notification links
openwisp/openwisp-notifications pull request #266
Opened 2024-03-03 09:10 UTC by Dhanus3133

Fixes: #249 

![image](https://github.com/openwisp/openwisp-notifications/assets/43700516/9fedc320-ad73-4d12-8fbf-2fec8c96e125)

2024-03-07 19:34 UTC, nemesifier requested changes
Thank you @Dhanus3133, it looks good.

Here's a few things to improve, see below.

The REST API is returning relative URLs as shown in the following screenshot:

![Screenshot from 2024-03-07 16-29-40](https://github.com/openwisp/openwisp-notifications/assets/841044/946ce6e9-8661-446c-984f-da129964f67d)

That's unintended, we only want this new behavior in the admin widget, the API may be hosted on a different domain and hence must return the full URL.

Please also add a new unit test which tests the new methods that allow returning the relative URLs.

Watch out also from build failures because of failed QA checks, please read the build output to find out how to run qa checks locally and how to fix common formatting and commit message format issues.

2024-03-07 19:34 UTC, nemesifier commented on openwisp_notifications/base/models.py
> +    def target_url(self, absolute_url=False):
If we turn these properties into methods which support passing arguments we have to change their name to `get_{property_name}`, for backward compatibility we can keep the properties and internally call the new method which passes `absolute_url=True`.

2024-03-08 08:47 UTC, Dhanus3133 commented
Updated with just the required notification widget changes, although the QA checks for the CSS files are failing for some reason.

2024-03-13 14:13 UTC, nemesifier requested changes
Works as expected now, thanks!
Take a look at the comments below for some minor code improvements.

If you can add a selenium browser test for this it would be great, let me know!

2024-03-19 13:40 UTC, Dhanus3133 commented
@nemesifier, I tried adding Selenium tests, but when the notification tab is clicked, it just loads. When I look into the console, it says it cannot find WS and returns 404 in the network.
![image](https://github.com/openwisp/openwisp-notifications/assets/43700516/6ea4ee4d-7ac0-46ef-815a-b45c20da0537)
Could you help me here? Thanks.

2024-03-19 19:37 UTC, nemesifier commented
> it just loads

Did you mean "it doesn't load"?

2024-03-20 03:12 UTC, Dhanus3133 commented
> Did you mean "it doesn't load"?

I meant the WebSocket connection is not found, so in the front end, it just waits, causing the spinning UI.

https://github.com/openwisp/openwisp-notifications/assets/43700516/1c21bb68-f2ec-4c4c-9fb5-da85fe4b112e

2024-03-20 11:39 UTC, nemesifier requested changes
The base test class `StaticLiveServerTestCase` does not support websockets.

Here's a rough outline of how we might structure these tests:

```python
from django.contrib.staticfiles.testing import StaticLiveServerTestCase
from channels.testing import ChannelsLiveServerTestCase

class SeleniumTestNotifications(StaticLiveServerTestCase, ChannelsLiveServerTestCase):
    # ... etc ...
```

Please consults these links for more information:

- [ChannelsLiveServerTestCase docs](https://channels.readthedocs.io/en/latest/topics/testing.html) 
- [StaticLiveServerTestCase docs](https://docs.djangoproject.com/en/5.0/ref/contrib/staticfiles/#specialized-test-case-to-support-live-testing)

2024-04-19 14:16 UTC, nemesifier reviewed
@Dhanus3133 I missed the latest updates on this, will review asap.

2024-04-22 18:19 UTC, nemesifier reviewed
Great work @Dhanus3133, I left some comments below, I am doing some quick tests locally  to verify some of my comments.

2024-04-22 18:19 UTC, nemesifier commented on openwisp_notifications/tests/test_notifications.py
> +class SeleniumTestNotifications(
I would move this to a new dedicated test file, it's possible that over time we'll be adding more tests for the widget.

2024-04-22 18:19 UTC, nemesifier commented on requirements-test.txt
> +selenium~=4.18.1
We already depend on selenium in openwisp-utils[selenium], we may want to look if we can avoid redefining this here: https://github.com/openwisp/openwisp-utils/blob/master/setup.py#L67

2024-04-22 18:19 UTC, nemesifier commented on tests/openwisp2/settings.py
> +        },
Are you sure this is really needed?

2024-04-22 18:48 UTC, nemesifier approved these changes
@Dhanus3133 I pushed some improvements, feel free to review the changes. Once the build passes I will merge. :+1:

2024-04-22 18:52 UTC, merged