[fix] prevent sending multiple identical notifications #277
openwisp/openwisp-notifications pull request #278
Opened 2024-06-04 20:36 UTC by kkreitmair

If a user is in several organizations,
they will receive multiple identical notifications. The reason for this is that the database query,
which determines which user should receive the notification, does a LEFT OUTER JOIN with the "openwisp_users_organizationuser" table. In this table, a user is multiple times listed,
when he is in several organizations.
Therefore the query returns such a user multiple times, which will then receive multiple identical notifications. This commit fixes this bug by adding a distinct to all user queries.

Fixes #277

2024-06-05 19:04 UTC, nemesifier requested changes
Thanks @kkreitmair for the patch.

The issue description and patch is missing a few things:

- Can you share a series of exact steps to replicate the issue?
- We'll need to replicate the steps to write a test, ensure it fails without the patch and ensure the test passes with your patch

2024-06-07 08:55 UTC, kkreitmair commented
@nemesifier I updated the issue comment by a description how to replicate the issue.
The test will follow soon.

2024-06-11 14:06 UTC, kkreitmair commented
@nemesifier I added the test.

In my patch, I naively added also a `.distinct()` to the [QuerySet](https://github.com/openwisp/openwisp-notifications/pull/278/files#diff-5930139e901f3ac3e29b49c3b4e03a54def94c49852ffe74c18b400d5dfa014cR117-R119), which is injected through a parameter of the function.
This can be a convenient functionality, but could be also seen as a bad practice, because normally the caller of the function should care about this.
So the question is if this change should stay or should be removed. What is your opinion on this?

2024-06-13 17:30 UTC, nemesifier approved these changes
I am not sure why we didn't spot this before, but thank you very much @kkreitmair for fixing it!

2024-06-13 17:32 UTC, merged